Allow empty srcs in cue_export
world-federation-of-advertisers/rules_cue pull request #6
Opened 2022-09-22 20:59 UTC by iverson52000

Allow empty srcs in cue_export so cue_dump can depend on cue_library in CMMS repo

2022-09-22 21:06 UTC, SanjayVas requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/rules_cue/6)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @iverson52000 and @SanjayVas)

___
*[`cue/defs.bzl` line 100 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/rules_cue/6#-NCb0F8gB9KC3vFZN04c:-NCb0F8gB9KC3vFZN04d:boacrc1) ([raw file](https://github.com/world-federation-of-advertisers/rules_cue/blob/1a2190f3c383237cbff75fbca82fb1829e75dc0e/cue/defs.bzl#L100)):*
> ```Starlark
> 
> def _cue_export_impl(ctx):
>     outfile = ctx.actions.declare_file(
> ```

Since srcs can now be empty, add a check here to `fail` if both `srcs` and `deps` are empty. See `_cue_string_field_impl` for an example.


<!-- Sent from Reviewable.io -->

2022-09-22 21:07 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/rules_cue/6)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @iverson52000 and @SanjayVas)

___
*[`cue/defs.bzl` line 140 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/rules_cue/6#-NCb0_Wc5yNGA25s0xgR:-NCb0_Wc5yNGA25s0xgS:b-iahptg) ([raw file](https://github.com/world-federation-of-advertisers/rules_cue/blob/1a2190f3c383237cbff75fbca82fb1829e75dc0e/cue/defs.bzl#L140)):*
> ```Starlark
>         "deps": attr.label_list(
>             doc = "cue_library dependencies.",
>             providers = [CueInfo],
> ```

I suppose this also should have `allow_empty = True`, so we can have `srcs` without `deps`.


<!-- Sent from Reviewable.io -->

2022-09-22 21:41 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/rules_cue/6)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`cue/defs.bzl` line 100 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/rules_cue/6#-NCb0F8gB9KC3vFZN04c:-NCb8ZDz51lEsO728iNL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/rules_cue/blob/1a2190f3c383237cbff75fbca82fb1829e75dc0e/cue/defs.bzl#L100)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Since srcs can now be empty, add a check here to `fail` if both `srcs` and `deps` are empty. See `_cue_string_field_impl` for an example.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-22 21:45 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/rules_cue/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @iverson52000)



<!-- Sent from Reviewable.io -->

2022-09-23 21:27 UTC, stevenwarejones approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/rules_cue/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)



<!-- Sent from Reviewable.io -->

2022-09-26 16:25 UTC, merged